#!/usr/bin/env ruby
#
# Little wrapper scripts that setups the environment before running the real executable.
#

pwd = Dir.pwd
file = __FILE__

while File.symlink?(file)
  file = File.expand_path File.readlink(file)
  Dir.chdir File.dirname(file)
end

Dir.chdir pwd
top = File.expand_path('../../..', file)

ENV['BUNDLE_GEMFILE'] = File.join(top, 'Gemfile')

$:.unshift File.join(top, 'vendor/bundle')

require 'bundler/setup'

load File.join(top, 'bin/stronghold-cli')
